[package]
name = "zc706"
version = "0.0.0"
authors = ["Astro <astro@spaceboyz.net>"]
edition = "2018"

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
debug = true

[features]
target_zc706 = []
target_cora_z7_10 = []
default = ["target_zc706"]

[dependencies]
r0 = "0.2"
volatile-register = "0.2"
bit_field = "0.10"
compiler_builtins = { version = "~0.1", default-features = false, features = ["mem", "no-lang-items"]}
smoltcp = { version = "0.5", default-features = false, features = ["proto-ipv4", "socket-tcp"] }
