[workspace]
members = [
  "libregister", "libcortex_a9",
  "libboard_zynq", "libsupport_zynq",
  "experiments",
]

[profile.dev]
panic = "abort"
lto = false

[profile.release]
panic = "abort"
debug = true
# Link-Time Optimization:
# turned off for producing unusable debug symbols.
lto = false
opt-level = 'z'  # Optimize for size.
