[package]
name = "libconfig"
version = "0.1.0"
authors = ["M-Labs"]
edition = "2018"

[dependencies]
libboard_zynq = { path = "../libboard_zynq" }
log = "0.4"
libcortex_a9 = { path = "../libcortex_a9" }

[dependencies.core_io]
git = "https://git.m-labs.hk/M-Labs/rs-core_io.git"
rev = "e9d3edf027"
features = ["collections"]

[dependencies.fatfs]
git = "https://git.m-labs.hk/M-Labs/rust-fatfs.git"
rev = "4b5e420084"
default-features = false
features = ["core_io"]

[features]
target_zc706 = []
target_coraz7 = []
target_ebaz4205 = []
target_redpitaya = []
target_kasli_soc = []
ipv6 = []
fat_lfn = [ "fatfs/alloc" ]
